# Uncomment this line to define a global platform for your project
 platform :ios, '9.0'

target 'Transactions' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Transactions
  pod 'Alamofire', '~> 3.4'
  pod 'SwiftyJSON'

  target 'TransactionsTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'Alamofire', '~> 3.4'
    pod 'SwiftyJSON'
  end

end
